In [1]:
from typing import List
import numpy as np
from vector_space_model import VectorSpaceModel

Preprocessed data not found. The system is going to make new indexes.
Stop words loaded successfully.
Parsing	ResearchPapers\1.txt
Parsing	ResearchPapers\11.txt
Parsing	ResearchPapers\12.txt
Parsing	ResearchPapers\13.txt
Parsing	ResearchPapers\14.txt
Parsing	ResearchPapers\15.txt
Parsing	ResearchPapers\16.txt
Parsing	ResearchPapers\17.txt
Parsing	ResearchPapers\18.txt
Parsing	ResearchPapers\2.txt
Parsing	ResearchPapers\21.txt
Parsing	ResearchPapers\22.txt
Parsing	ResearchPapers\23.txt
Parsing	ResearchPapers\24.txt
Parsing	ResearchPapers\25.txt
Parsing	ResearchPapers\26.txt
Parsing	ResearchPapers\3.txt
Parsing	ResearchPapers\7.txt
Parsing	ResearchPapers\8.txt
Parsing	ResearchPapers\9.txt

Saving all computed indexes on the drive.
Total entires in the collection	20.
5294


In [2]:
vector_space_model = VectorSpaceModel(
    documents_path="ResearchPapers",
    stop_words_file_path="Stopword-List.txt",
)
vector_space_model.initiate()

Preprocessed data not found. The system is going to make new indexes.
Stop words loaded successfully.
Parsing	ResearchPapers\1.txt
Parsing	ResearchPapers\11.txt
Parsing	ResearchPapers\12.txt
Parsing	ResearchPapers\13.txt
Parsing	ResearchPapers\14.txt
Parsing	ResearchPapers\15.txt
Parsing	ResearchPapers\16.txt
Parsing	ResearchPapers\17.txt
Parsing	ResearchPapers\18.txt
Parsing	ResearchPapers\2.txt
Parsing	ResearchPapers\21.txt
Parsing	ResearchPapers\22.txt
Parsing	ResearchPapers\23.txt
Parsing	ResearchPapers\24.txt
Parsing	ResearchPapers\25.txt
Parsing	ResearchPapers\26.txt
Parsing	ResearchPapers\3.txt
Parsing	ResearchPapers\7.txt
Parsing	ResearchPapers\8.txt
Parsing	ResearchPapers\9.txt

Saving all computed indexes on the drive.
Total entires in the collection	20.


1

In [3]:
X = []
doc_seq = []
for i in vector_space_model.vsm_index:
    doc_seq.append(int(i[0]))
    X.append(i[1])
y = vector_space_model.make_y(doc_seq=doc_seq)
X = np.array(X)


# from sklearn.preprocessing import Normalizer

# transformer = Normalizer().fit(X)  # fit does nothing.
# B = transformer.transform(X)


In [178]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# X = StandardScaler().fit_transform(X)
# print(X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.48
)
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)
score = knn.score(X_test, y_test)
print(score)

y_pred = knn.predict(X_test)
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

0.7
[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 2 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]]


In [179]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                                     precision    recall  f1-score   support

Explainable Artificial Intelligence       1.00      1.00      1.00         3
                  Feature Selection       0.50      1.00      0.67         3
                      Heart Failure       0.00      0.00      0.00         2
            Time Series Forecasting       1.00      1.00      1.00         1
                  Transformer Model       0.00      0.00      0.00         1

                           accuracy                           0.70        10
                          macro avg       0.50      0.60      0.53        10
                       weighted avg       0.55      0.70      0.60        10



d:\Text Classification and Clustering\.env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Text Classification and Clustering\.env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\Text Classification and Clustering\.env\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is",

In [185]:
"""
    Class Name: "Explainable Artificial Intelligence"
    Documents: 1,2,3, and 7
    Class Name: "Heart Failure"
    Documents: 8,9, and 11
    Class Name: "Time Series Forecasting"
    Documents: 12,13,14,15, and 16
    Class Name: "Transformer Model"
    Documents: 17,18, and 21
    Class Name: "Feature Selection"
    Documents: 22,23,24,25, and 26
"""

li = {
    "17": """


This article describes our experiments in neural machine translation using the recent Ten-


sor2TensorframeworkandtheTransformersequence-to-sequencemodel(Vaswanietal.,2017).


We examine some of the critical parameters that a?ect the ?nal translation quality, memory


usage, training stability and training time, concluding each experiment with a set of recom-


mendations for fellow researchers. In addition to con?rming the general mantra �more data


and larger models�, we address scaling to multiple GPUs and provide practical tips for im-


proved training regarding batch size, learning rate, warmup steps, maximum sentence length


andcheckpointaveraging. Wehopethatourobservationswillallowotherstogetbetterresults


given their particular hardware and data constraints.


""",

    "9": """


    The New York


Heart Association (NYHA) classification has been used


for over three decades as a summary measure of theclinicians� impression of symptoms in patients with CHF[4]. NYHA class predicts outcome in patients with heart


failure. However, this classification is based not only onfunctional limitation due to symptoms but is alsoinfluenced by knowledge of the severity of cardiac


dysfunction, prior medical history and the likely prog-


nosis. However, the degree and extent of dyspnoea and


fatigue are often poorly documented in patient records.This may reflect the lack of objective methods formeasuring symptoms and their variable relationship withenvironment, activity and mood. These factors and theability to induce temporary relief of severe symptomsmay have reduced the importance of symptoms as atarget of therapy for clinical trialists.


Symptoms are subjective, and clinicians should recog-


nise and value their importance to patients. They reflecthow the patient feels. They are the cry for help,reflecting not only the physical aspects of the diseasebut the associated impact on lifestyle, anxiety, depressionand expectations of the patient. For these reasons,symptoms will vary markedly amongst patients andwithin the same patient from one time to another.


Worsening conditions will often provoke emotional


responses that make the patient feel more severelyaffected by symptoms. Once re-stabilised, even if notimproved, given time to adjust lifestyle and expectations,symptoms may abate even if functional capacity does notrecover. Patients learn to live with their symptoms andthereby report less severity. However, the perceiveddiscomfort of symptoms, as well as the actual limitation


they cause are both of interest to health professionals.


Relief of symptoms is an important target of therapy forpatients with CHF [5]as recognised by the European


agency for the evaluation of medical products (EMEA) aswell as the American Food and Drug administration(FDA) [6].


1388-9842/$ - see front matter D2005 European Society of Cardiology. Published by Elsevier B.V. All rights reserved.


doi:10.1016/j.ejheart.2005.07.003The European Journal of Heart Failure 7 (2005) 699�703


www.elsevier.com/locate/heafai2. Which symptoms?


Breathlessness and fatigue are the classical symptoms


of heart failure [7�9] . Probably because of the NYHA


classification, other symptoms are rarely documented inpatients with CHF, but as many as 23 differentsymptoms have been reported by patients during theirlast 6 months of life [9]. Symptoms such as difficulty


concentrating and bodily pain (other than chest pain) are


common [10]. Women and men with CHF experience


similar symptoms, but they are perceived in differentways; physical and social restrictions affecting daily lifeactivities are most problematic for men, whereas restric-tions affecting the ability to support family and friendsare most difficult for women [11�13] .


3. Symptom assessment


Symptoms reflect the patient�s personal subjective


experience, which is then interpreted, subjectively, byhealth professionals. Not surprisingly, there is disparitybetween the assessment of symptoms by patients comparedto physicians and nurses [14�16] . According to Tiesinga et


al.[17], nurse assessment of the intensity of patients


fatigue relates poorly with the patients own perceptions,while the patients� relatives assessed fatigue more accu-rately. Obviously, knowledge about personal factors isimportant when assessing symptoms. Of even greaterconcern is the poor reproducibility of symptom assessmentby physicians [16].


It has often been assumed that dyspnoea is a sensation


that varies only in the degree of intensity, but certain


descriptors of shortness of breath have been reported to bemore likely to be endorsed by patients with specificconditions [17]. For example, patients with chronic


obstructive pulmonary disease (COPD) chose, bMy breath-


ing requires effort Q, whereas patients with heart failure


chose, bI feel that I am suffocating Q, to characterize their


personal experiences of dyspnoea [18,19] . When compar-


ing descriptors of breathlessness among men and women,


we found that the women did not choose any particulardescriptor whereas men scored the following threedescriptors significantly higher; My breath does not go


in all the way ,I feel that I am suffocating andI cannot get


enough air [14]. Furthermore, the physicians recognised


and assessed symptoms of CHF with greater accuracy inmen. A major reason for failing to make an accurate


diagnosis in CHF is that symptom presentations mirror our


cultural and social contexts. The clinical understanding ofsymptoms associated with coronary disease is derivedprimarily from studies in male patients. Clinical trials oftenfocus on patients with left ventricular systolic dysfunctionleading to a higher proportion of men. This may under-value the importance of heart failure and its symptomburden in women.4. Self-assessed symptoms


The clinicians� task is difficult because symptoms are


subjective and meaningful. Studies consistently show adifference in patients� self-assessed functional classifica-tion compared to investigator reported NYHA classifica-tion [20,21] .(Fig. 1 ). Recently, the COMET trial reported


that the severity of patient self-assessed symptoms,


independently predicted hospitalisation and mortality over


5 years [21]. Breathlessness, fatigue and angina were


rated by the patients ( n=3029) using a 5-point scale as


follows: (1) Asymptomatic; (2) Walking upstairs at normalpace; (3) Walking at normal pace on the flat; (4) Walkingslowly on the flat or during washing or dressing and (5)At rest. In a multivariate Cox regression analysisincluding 16 baseline covariates, amongst symptoms,


breathlessness predicted an increase in mortality and all-


cause hospitalisation, whilst fatigue predicted the develop-ment of worsening heart failure. Clearly, symptomsreported by patients are not only important targets fortherapy in their own right, but also indicate the need fortreatment to improve prognosis.


Patient reported symptoms are readily available, inex-


pensive to acquire, valid (because they reflect the patients�


experience), predict outcome and may be less operator-


dependent than physical signs. Helping the physician andnurse to understand the structure of the patients� realityshould improve the therapeutic alliance between patientsand caregivers.


5. Disease and illness


A distinction between disease and illness must be


made. Disease is defined as an abnormality in thestructure and function of body organs and systems andcan often be identified by signs of bodily disorder such asoedema or reduced ejection fraction [22]. Illness means


experienced reduction in states of well-being and socialfunction manifesting as symptoms [22]. Disease and


NYHA%


020406080100


III


II


IIV


Self assessed function


Fig. 1. Patients� self-assessed functional classification compared to


conventional NYHA classification (modified after Ref. [20]).Editorial 700


 18790844, 2005, 5, Downloaded from https://onlinelibrary.wiley.com/doi/10.1016/j.ejheart.2005.07.003 by Higher Education Commission,, Wiley Online Library on [13/02/2024]. See the Terms and Conditions (https://onlinelibrary.wiley.com/terms-and-conditions) on Wiley Online Library for rules of use; OA articles are governed by the applicable Creative Commons License


illness do not have a one-to-one relationship, signs can be


identified without experiences of symptoms and similardegrees of organ pathology can generate quite differentsymptoms, as is well known in heart failure [23,24] .


Illness may occur in the absence of detectable disease.Accordingly, the course of the disease may be verydifferent from that of the accompanying illness. A modelof clinical practice, integrating both the disease and illness


perspectives, has been developed by the medical anthro-


pologists Byron J. Good and Mary-Jo Delvecchio-Good[2]. They state that whatever the biological correlates or


grounds of a disease, illness becomes an interpretedpersonal experience for the patient. At present, the diseaseis primarily considered as an object for therapeuticattention for the care provider. We found this modeluseful in exploring symptoms in a structured way and


have therefore modified it in order to match care and


treatment for patients with CHF. The model is describedstep by step in Table 1 .


The first step; The pathological entity identifies the


symptoms, such as breathlessness, and tiredness or signssuch as ankle swelling. The next step; Structure of


relevance means information that reveals the meaning of


illness to a patient, for example the patient explains that


he or she cannot manage the stairs at home because of


the breathlessness. The elicitation procedure in the


disease perspective is when the physician confirms thesuspected diagnosis with for example echocardiography,from the illness perspective it means listening to thepatient�s personal explanation of the symptoms and signs.The interpretative goal is diagnosis and explanation from


the disease point of view and from the illness perspectiveit means the health professional�s understanding of thepatient�s interpretation of their condition and the treat-ment. And finally, The therapeutic goal which is to


intervene in the disease process in the disease-orientedapproach while, from the illness perspective it meanstrying to reach concordance between health professionals


and patients� view on illness and treatment.


6. Adherence to prescribed treatment


""",
    "9_2": """ymptoms are important for the interpretation and


understanding of patients with CHF. They reflect eitherthe disease itself or the patient�s perception of the illness.


Recognition of symptoms and appreciation of their


importance should be the reason for a structured assessmentin order to provide optimal care for patients with CHF.


References


[1] Eisenberg L, Kleiman A, editors. The relevance of social science for


medicine. London 7D. Reidal Publishing Company, 1980.


[2] Good BJ, Delvecchio-Good MJ. The meaning of symptoms: a cultural


hermeneutic model for clinical practice. In: Eisenberg L, Kleinman A,


editors. The relevance of social science for medicine. London 7D.


Reidal Publishing Company, 1980. p. 165�96.


[3] Foucault M. The birth of the clinic An archae""",
    "26": """to construct the objective loss function LD(w). After that,


the correct answer and the most offending incorrect answer


for a sample should be explic itly identi?ed. To summarize,


the following issues are critical to the feature weightingalgorithm design: 1) using appropriate criteria to determine


the correct answer and the most offending incorrect answer


for each sample and 2) properly designing the structure of an


energy function E, which is needed in the per-sample loss


function of (5) and consequently (2). By properly addressingthese issues, learning leads to ?nding the appropriate energy


function such that the per-sample loss function of (5) will be


pushed down for correct answers and pulled up for incorrectanswers while maintaining an energy gap or margin.


To address the ?rst issue of developing appropriate cri-


teria to determine the correct answer and the most offend-


ing incorrect answer for each sample, we resort to the


nearest neighbor (NN) classi?cation scheme. Note that, theNN classi?er is a nonlinear mapping between input patterns


and class labels. It is a simple algorithm but has received


considerable attention aga in recently since they have been


demonstrated highly ef?cient in some state-of-the-art real-


world applications [14], [15]. Additionally, the NN classi?er


can be viewed as an energy-based learning where the energy


function is a sample distance measure. Consider a sample


x


i, its NN in the same class denoted by NH(xi)can be""",
}
from sklearn.preprocessing import Normalizer



temp = vector_space_model.transform_query(user_query=_17)[1]


print(temp)



# transformer = Normalizer().fit([temp])  # fit does nothing.


# B = transformer.transform([temp])


# output = knn.predict(B)


output = knn.predict([temp])


print(output[0])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 